### ISSUE TITLE
Add one of thin, falcon, puma, HTTP, or webrick to Gemfile

### ISSUE THREAD

**Issue by mslinn** [pabuisson/blog-sinatra-warden#3]
Ruby 3.0 removed `webrick` from default dependencies. To ensure this program works the same on all versions of Ruby, add the following to `Gemfile`:

```ruby
gem 'webrick', require: false
```

... otherwise, the following error is encountered with Ruby 3.x:
```
lib/rack/handler.rb:45:in `pick': Couldn't find handler for: thin, falcon, puma, HTTP, webrick. (LoadError)
```

**Comment by pabuisson** [comment]
Indeed! Thanks for the issue 👍 

Added puma in 0ed09a83bb08dd8fef1c0dada6c6ad45b8d7b154 + updated the README. I'll also update the blog post itself to reflect this.
